name: Build MineBot IPA

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Xcode project
        run: swift package generate-xcodeproj

      - name: Build app
        run: |
          xcodebuild \
          -project MineBot.xcodeproj \
          -scheme MineBot \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          build

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/MineBot.app Payload/
          zip -r MineBot.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MineBot
          path: MineBot.ipa
